### ISSUE TITLE
Plots going outside of the boundary of the plot

### ISSUE THREAD

**Issue by jolespin** [marcharper/python-ternary#108]
I'm trying to just do a simple of values between 0 and 1 but it's exceeding the plot boundary. 

```
x = np.random.RandomState(0).choice(np.linspace(0,1), size=100)
y = np.random.RandomState(1).choice(np.linspace(0,1), size=100)
z = np.random.RandomState(2).choice(np.linspace(0,1), size=100)

df = pd.DataFrame([x,y,z]).T

# Scatter Plot
with plt.style.context("seaborn-white"):
    fig, ax = plt.subplots(figsize=(5,5))
    tax = ternary.TernaryAxesSubplot(ax=ax)
    points = df.values
    tax.scatter(points, marker='s', color='red', label="Red Squares")
    tax.boundary(linewidth=1.0)
#     tax.ticks(axis='lbr', linewidth=1, multiple=5)
    tax.clear_matplotlib_ticks()
    tax.get_axes().axis('off')
```

![image](https://user-images.githubusercontent.com/9061708/61349577-7e697500-a819-11e9-87db-2fca8b646863.png)

**Comment by marcharper** [comment]
` x + y + z = scale` needs to be true for every point. I don't think that the random data generation process you have will guarantee that. Probably you can draw your `x` values, draw `y` from `1-x`, and compute `z` exactly as `z = 1 - x - y`.

**Comment by jolespin** [comment]
Oh ok, do the x y z coords need to sum to 1? That actually makes a lot of sense after reading some material about simplexes.
