### ISSUE TITLE
Additional control over heatmap color bar

### ISSUE THREAD

**Issue by Npikeulg** [marcharper/python-ternary#111]
Hello,

Would it be possible to add additional control for fontsize for the colorbar label and fontsize for the colorbar ticks?  I believe these additional features would be easy to add.  

In colorbar_hack you need to adjust the first if statement to :
if cbarlabel is not None:
        cb.set_label(cbarlabel,size=cbfontsize)
        cb.ax.tick_params(labelsize=cblabelsize)
and allow colorbar_hack to take some additional keywords (cbfontsize, cblabelsize).

Nice program, thanks for the work!

**Comment by bmondal94** [comment]
Although this  seems quite an old thread but just for the future reference,
I return the colorbar object (cb) from colormapping.colorbar_hack(),  heatmapping.heatmap(), heatmapping.heatmapf(), plotting.scatter() and finally from ternary_axes_subplot.scatter(), ternary_axes_subplot.heatmap(), ternary_axes_subplot.heatmapf(). Then one can use the returned cbar to update properties.

**Comment by marcharper** [comment]
Closing, ref'd in #102
