### ISSUE TITLE
Add bbox_inches argument to tax.savefig()

### ISSUE THREAD

**Issue by gileshd** [marcharper/python-ternary#114]
The `bbox_inches='tight'` kwarg for the native matplotlib `ax.savefig` method is a really useful tool to control figure margins when exporting plots.

It looks like this isn't exposed to the `TernaryAxesSubplot.savefig` method, it would be useful to add this as an optional argument.

Currently I have been able to get this functionality by using `figure.savefig(...,bbox_inches='tight')` but it would be nice to be able to pass it directly to the axes object as this is most similar to the usual workflow in matplotlib.

It seems like this would be pretty simple to do and I'm happy to have a go at a pull request if desired.

**Comment by marcharper** [comment]
Sure, go ahead. Probably the best thing to do is pass through all the arguments, something like

```
    def savefig(self, filename, **kwargs):
        ...
        fig.savefig(filename, **kwargs)
```
