### ISSUE TITLE
how to solve the problem of duplication of the label?

### ISSUE THREAD

**Issue by machel7** [marcharper/python-ternary#118]
labels of the axe at the corner is dupulicated with lable of title.
how can we adjust the the lable to delete the first and the last label of the axe?
![image](https://user-images.githubusercontent.com/23093272/71794732-d755ef80-307d-11ea-9210-e1a27718fbea.png)

**Comment by marcharper** [comment]
You can explicitly [set the ticks](https://github.com/marcharper/python-ternary/blob/master/ternary/ternary_axes_subplot.py#L359) with `tax.ticks()`.

Changing to integers for the tick values may also improve the appearance of the plot.
