### ISSUE TITLE
Corner label positions are not as expected

### ISSUE THREAD

**Issue by jdh10791** [marcharper/python-ternary#119]
When using corner labels with non-default offsets, the left and right corner labels seem to move in unexpected directions. Increasing the offset of the left corner label moves it up and to the left, whereas I would expect it to move down and to the left (such that the left corner of the ternary boundary would be pointing toward the label). Similarly, increasing the offset of the right corner label moves it up and to the right, while I would expect it move down and to the right. The behavior of the top corner label is as expected.

Code to reproduce:

    fig, ax = plt.subplots(figsize=(7,6))
    tax = ternary.TernaryAxesSubplot(ax=ax)

    tax.boundary()
    tax.left_corner_label('Left',size=12,offset=0.5)
    tax.right_corner_label('Right',size=12,offset=0.5)
    tax.top_corner_label('Top',size=12,offset=0.5)
    ax.axis('off')

I'm using python-ternary 1.0.6, matplotlib 3.1.1.

**Comment by marcharper** [comment]
These functions accept a [position parameter](https://github.com/marcharper/python-ternary/blob/fb96c83077ecd2e43292c56004d95e9fd06ed982/ternary/ternary_axes_subplot.py#L215) to place the corner label at a specific location.

**Comment by jdh10791** [comment]
Ah, thanks for pointing that out. I can certainly use the position parameter to place the labels manually, but wasn't sure if the default behavior with `offset` was as expected or not. Thanks for this great package!

**Comment by marcharper** [comment]
I've tried the direction that you suggested but it also has downsides -- it tends to make the whitespace of the plot too large, and for longer labels it really needs to position the center of the text rather than the start, which is tricky with the current implementation. So for now manual positioning is the fallback.
