### ISSUE TITLE
How to determine the intersection of several curves

### ISSUE THREAD

**Issue by mohamedELamine** [marcharper/python-ternary#122]

**Comment by marcharper** [comment]
This is a plotting library and doesn't have such capabilities.

**Comment by mohamedELamine** [comment]
Is there no solution? can you help me please

**Comment by mohamedELamine** [comment]
Can you show the coordinates of each point we plotted on the curve?

**Comment by mohamedELamine** [comment]
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 17 14:01:06 2020

@author: mohamed
"""

import ternary
 
     
scale =100
figure, tax = ternary.figure(scale=scale)
 
 
tax.boundary(linewidth=1.0)
tax.gridlines(color="b", multiple=10, linewidth=0.5, ls='-')
fontsize = 12
 
tax.ticks(multiple=10,offset=0.02)
tax.set_axis_limits({'b': [65, 75], 'l': [15, 30], 'r': [10, 25]})
tax.get_ticks_from_axis_limits(multiple=5)
tick_formats = "%.1f"
 
tax.right_corner_label("C2C4", fontsize=fontsize)
tax.top_corner_label("C3C4", fontsize=fontsize)
tax.left_corner_label("C1C4", fontsize=fontsize)
     
  
     
#C1C2C3
p01 = (31.48616699,	27.75450385	,40.75932916)
p02 = (31.02520316,	29.4240961	,39.55070074)
p03 = (30.68322854,	30.66271425	,38.65405721)
p04 = (30.41943748,	31.61815473,	37.96240779)
p05 = (32.72814934,	34.70993858	,32.56191208)
p06 = (33.26789257,	28.9662689	,37.76583853)
p07 = (33.69497585,	34.61891734	,31.6861068)
p08 = (30.14040347,	34.25568936,	35.60390718)
o01=  (29.67359444	,42.78987657,	27.53652899)
o02=  (25.27649543,	36.4491778,	38.27432677)
o03=  (27.84064523	,30.0023257,	42.15702907)
o04=  (36.44691744	,26.42402067,	37.12906189)
o05=  (42.56565497	,30.86010631	,26.57423872)
o06=  (38.54382387	,37.39281384	,24.06336229)
omega1 = (o01,o02,o03,o04,o05,o06) 
points1 = (p01, p02,p03,p04,p05,p06,p07,p08)
tax.plot(omega1, linewidth=2.0, label="Curve"  )
tax.scatter(points1 , linewidth=3., marker='s',s=25, color='red', linestyle=":")
 

#C1C2C4
p1 = (33.1543281,  29.2249586, 37.6207133)
p2 = ( 34.300021,	 32.5299115,	 33.1700675)
p3 = ( 35.1931143,	 35.1695847	, 29.637301)
p4 = ( 35.9070992,	 37.3220649	, 26.7708359)
p5 = ( 38.9603905,	 41.3195609	, 19.7200487)
p6 = ( 37.2906935,	 32.4689113,	 30.2403952)
p7 = ( 40.0194275,	 41.1167901,	 18.8637824)
p8 = ( 39.2884576,	 44.652793,	 16.0587494)
o1 = (40.95,	59.05	,0.0000)
o2 = (27.53,	39.70	,32.77)
o3 = (30.60,	32.97	,36.43)
o4 = (39.59,	28.70	,31.71)
o5 = (57.97,	42.03	,0.0000)
o6 = (50.76,	49.24	,0.0000)
omega = (o1,o2,o3,o4,o5,o6) 
points = (p1, p2,p3,p4,p5,p6,p7,p8)
tax.plot(omega, linewidth=2.0, label="Curve")
tax.scatter(points , linewidth=3., marker='o',s=25, color='green', linestyle=":")
 
p11=(29.16106163	,33.08949398,	37.74944439)
p12=(30.84659007,	29.83040383	,39.3230061)
p13=(32.23818556	,27.14885653	,40.61295791)
p14=(33.40544704,	24.90570832	,41.68884464)
p15=(39.98277535,	20.23753525,	39.7796894)
p16=(33.94271134,	38.53189536	,27.5253933)
p17=(41.46372973,	19.54457684	,38.99169343)
p18=(38.6099185,	15.78140356,	45.60867794)
o11=(32.07	,38.18,	29.76)
o12=(26.99,	32.14,	40.87)
o13=(39.77,	0000	,60.23)
o14=(49.54	,0000,	50.46)
o15=(61.56	,0000	,38.44)
o16=(41.23,	33.03,	25.74)
omega2 = (o11,o12,o13,o14,o15,o16) 
points2 = (p11, p12,p13,p14,p15,p16,p17,p18)
tax.plot(omega2, linewidth=2.0, label="Curve")
tax.scatter(points2 , linewidth=3., marker='o',s=25, color='b', linestyle=":")
 
#C4C2C3
p21= (34.27403811,	26.62515557	,39.10080632)
p22= (30.31295252,	29.72793652,	39.95911096)
p23= (27.15470943,	32.22357709	,40.62171348)
p24= (24.58211311,	34.2706976,	41.14718929)
p25= (19.75915061,	41.40149151,	38.83935788)
p26= (28.78890358,	30.91045446,	40.30064196)
p27= (19.32485965,	42.12178566	,38.55335469)
p28= (14.99111833,	41.68414917,	43.3247325)
o21= (0	,60.84468022	,39.15531978)
o22= (0,	48.77873169,	51.22126831)
o23= (0	,41.57787413	,58.42212587)
o24= (31.47548489,	28.49103664	,40.03347847)
o25= (37.24878236	,33.71692054,	29.0342971)
o26= (33.43685248	,40.50013425	,26.06301327)
omega3 = (o21,o22,o23,o24,o25,o26) 
points3 = (p21, p22,p23,p24,p25,p26,p27,p28)
tax.plot(omega3, linewidth=2.0, label="Curve")
tax.scatter(points3 , linewidth=3., marker='D',s=25, color='black', linestyle=":")
 
tax.get_axes().axis('off')

tax.ax.set_position([1,  1,1.2, 1.3])
tax.resize_drawing_canvas()
 
tax.clear_matplotlib_ticks()
tax.show()
