### ISSUE TITLE
overlay heatmap and scatter

### ISSUE THREAD

**Issue by anhvt2** [marcharper/python-ternary#129]
Hi, thank you for developing the library, I really enjoy it. I'm trying to overlay a heatmap with some scatter plots (and legends) on the top. It looks like heatmap is overriding the scatter plots, and I can only see the heatmap. Small reproducible code is as below (please fill in some missing values). Please let me know if it is possible to do so.

```python
tax.set_title("prediction", fontsize=fontsize)
tax.left_corner_label("x", fontsize=fontsize)
tax.right_corner_label("y", fontsize=fontsize)
tax.top_corner_label("z", fontsize=fontsize)

tax.left_axis_label("x", fontsize=fontsize, offset=offset)
tax.bottom_axis_label("y", fontsize=fontsize, offset=offset)
tax.right_axis_label("z", fontsize=fontsize, offset=offset)
# tax.ticks(axis='lbr', linewidth=1, multiple=3)

# cmap = 'coolwarm', 'seismic', 'Greys', 'PiYG', 'viridis' # https://matplotlib.org/tutorials/colors/colormaps.html
# tax.gridlines(multiple=1, color="blue")
tax.scatter( inp1, marker='o', s=10, color='b', label='1')
tax.scatter( inp2, marker='s', s=10, color='r', label='2')
tax.heatmap(d, style="triangular", cmap='coolwarm') # 'triangular' or 'dual-triangular' or 'triangular' or hexagonal 

tax.legend(fontsize=12, markerscale=1, loc='best')

tax.boundary(linewidth=1.0)
tax.get_axes().axis('off')
tax.clear_matplotlib_ticks()
tax.show()
```

**Comment by marcharper** [comment]
Hi, see #121 for a solution

**Comment by anhvt2** [comment]
@marcharper thanks a lot for your prompt response.

I hacked through your package and added ```alpha``` to control the transparency in ```ternary_axes_subplot.py``` and ```heatmapping.py```, even though the solution is not as great as yours. Thanks again!

**Comment by DavidRRice** [comment]
@marcharper @anhvt2 I would also like an alpha kwarg on the heatmap. I would like to overlay multiple heatmaps on a single ternary.

(I haven't commented before and like to also drop a note that I love the package and have two publications in the works using it!)

**Comment by marcharper** [comment]
@DavidRRice 
Do you want just the heatmap content (the colored subregions) to have alpha applied? I think that should be fine. It wouldn't apply to the axes and other plot dressings though.

**Comment by DavidRRice** [comment]
I'm trying to overlay the two attached heatmaps (instead of overlaying a heatmap and scatter). Maybe I can do it with the RGBA option, I was just beginning to play with it when I saw this issue, but it seems more straight forward to me if heatmap took a constant alpha value.

Thank you for the wicked fast response!

[nolabels1.pdf](https://github.com/marcharper/python-ternary/files/5638956/nolabels1.pdf)
[nolabels.pdf](https://github.com/marcharper/python-ternary/files/5638958/nolabels.pdf)

**Comment by marcharper** [comment]
Gotcha. So I think adding a simple alpha option to the heatmap function should be fine. It would also be possible at the plot level (in TernaryAxesPlot) but that's a bigger change and I'm not sure it makes sense to e.g. overlay multiple axes.
