### ISSUE TITLE
Tick Formatting

### ISSUE THREAD

**Issue by fboschetty** [marcharper/python-ternary#131]
Is it possible to specify tick label placement?
I want to remove the first and last of the tick labels on the axes. 
i.e. for scale = 100, remove the 0 and 100 tick labels but keep the intermediate labels.

**Comment by marcharper** [comment]
Yes you can set the ticks explicitly to be whatever you want using `tax.ticks(...)`. See [here](https://github.com/marcharper/python-ternary/blob/master/ternary/ternary_axes_subplot.py#L359).
