### ISSUE TITLE
Rasterized option for pdf/svg/eps export

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [marcharper/python-ternary#132]
Working with huge number of data, it will be nice if we can have `rasterized=True/False` option, similar to the one implemented in `matplotlib`.

Expected behavior:
- Axes labels, ticks and labels are all in vector format.
- The scattered dots inside the triangle getting blurry, meaning they will be counted as the single object with png format.
- The exported pdf file will be easier to render and print.

Thanks.

**Comment by marcharper** [comment]
Since this library is on top of matplotlib you should be able to pass through such options. For example, saving a file in SVG should work just fine.
