### ISSUE TITLE
The shape of the triangle

### ISSUE THREAD

**Issue by SleepyPepperHead** [marcharper/python-ternary#137]
Hi guys,
My plot is a squished triangle instead of a equilateral triangle.
Is there a way to adjust it to a equilateral triangle?
![image](https://user-images.githubusercontent.com/60811549/84127030-47bfcd00-aa71-11ea-8b54-f15000dc1bca.png)

**Comment by marcharper** [comment]
You can adjust the figure size away from the default. If you use `plt.show()` in interactive mode you should be able to resize the window as you please, otherwise when you create a mpl figure you can use something like `figsize=(10, 10)`.

**Comment by SleepyPepperHead** [comment]
Maybe just a parameter to cast the plot to equilateral triangle will help a lot

**Comment by marcharper** [comment]
It's generally not possible unfortunately. If you use a ternary plot as a subplot in a figure, the figure size determines the subfigure size, so the only way to ensure an equilateral triangle would be to shrink the content of the ternary subfigure to the lowest dimension (assuming that's possible to determine), which could produce tiny plots and would also be unintuitive.

Matplotlib controls the figure sizes; ternary just plots within the axes that it is given. If you find some other solution I'll consider it.
