### ISSUE TITLE
Change default orientation

### ISSUE THREAD

**Issue by darrentsmith** [marcharper/python-ternary#138]
Hello everyone,

     The default plot orientation seems to be Z (lower-left), Y (top), and X (lower-right).  I would like to instead set the plot to a X-Y-Z orientation.  I can sometimes work around this by switching my x and z values; however, this works for points but not when drawing lines.

     How can do this?  My apologies if I'm overlooking the obvious.  I've read some discussion about this but I'm still not sure what the final answer is.  

     Thank you.

**Comment by marcharper** [comment]
See [here](https://github.com/marcharper/python-ternary#axes-ticks-and-orientations)
