### ISSUE TITLE
Kernel density estimation

### ISSUE THREAD

**Issue by SleepyPepperHead** [marcharper/python-ternary#139]
Hi guys.
Your program is real a nice job!
I wonder is it possible to add Kernel density estimation in your ternary plot.
See the picture blow
![image](https://user-images.githubusercontent.com/60811549/84560128-83a9a980-ad73-11ea-99fd-00fc1adb24be.png)
![image](https://user-images.githubusercontent.com/60811549/84560146-a1770e80-ad73-11ea-879a-3be0990b921e.png)
![image](https://user-images.githubusercontent.com/60811549/84560150-ab990d00-ad73-11ea-85df-eb5dffa3ceaa.png)

**Comment by marcharper** [comment]
Hi, this library only plots data, it doesn't include any statistical functions like KDEs. However it is possible to plot a heatmap of a function using `heatmapf`, so if you are able to obtain a density estimation or interpolation from another package you should be able to plot it with ternary.
