### ISSUE TITLE
Default value for `scientific` in TernaryAxesSubplot.heatmapf is True 

### ISSUE THREAD

**Issue by c56pony** [marcharper/python-ternary#142]
Why `True` the default value of the argument `scientific` in `TernaryAxesSubplot.heatmapf` is?
The default value for all other similar methods (`ternary.heatmapf`, `ternary.heatmap`, `TernaryAxesSubplot.heatmap`) is `False`.

If you have no problem unifying them to `False`, I can make a pull request.

**Comment by marcharper** [comment]
Sure, sounds good.
