### ISSUE TITLE
Permutation breaks hexagonal heatmap style

### ISSUE THREAD

**Issue by r-menezes** [marcharper/python-ternary#148]
It seems that the permutation feature breaking inside heatmaps with hexagonal style.

To Replicate:
```{python}
import ternary
scale=5
aux = dict({(i,j,k): k for i, j, k in  ternary.helpers.simplex_iterator(scale)})

# works fine
ternary.heatmap(aux, scale, style="h", permutation="012")
ternary.heatmap(aux, scale, permutation="210")

# bug
ternary.heatmap(aux, scale, style="h", permutation="210") # any permutation besides '012' results in the bug
```

Results (added titles):
![Null Permutation Works](https://user-images.githubusercontent.com/38216046/91593680-f7049580-e936-11ea-98fd-5ae71802c402.png)

![Permutation in Triangular Style Works](https://user-images.githubusercontent.com/38216046/91594760-c9b8e700-e938-11ea-8197-c72e37f4fbd0.png)

![Bug](https://user-images.githubusercontent.com/38216046/91594837-ebb26980-e938-11ea-8c85-9938a3e4cc31.png)

**Comment by marcharper** [comment]
Thanks. This is now fixed on the main branch. I'll push a new version of the library soon.
