### ISSUE TITLE
Add alpha kwarg option to heatmap

### ISSUE THREAD

**Issue by marcharper** [marcharper/python-ternary#161]
See discussion at #129

**Comment by marcharper** [comment]
This turns out to be more subtle than anticipated. Currently when the library draws heatmaps the polygons composing the heatmap overlap slightly on the boundaries. With `alpha=1` polygons rendered later simply slightly overwrite the ones already rendered. However when `alpha < 1` the correct color for the common edge is determined by the two colors and their alphas. So to do this correctly, and have plots that look nice, would require rendering the polygons in a particular order and carefully calculating the edge colors.

A better way to solve the issue would be to utilize matplotlib's heatmapping / hexbining capabilities, which probably handle this correctly. However that requires a significant rewrite of how the entire library works. See #25 .

**Comment by DavidRRice** [comment]
I was afraid of that. I'll link the images here also; I noticed they were overwriting each other. Alpha seems very difficult when blending. However, could you only do the blending with RGB then add a constant alpha to all values? Ah, but the overlap still is there and would be twice the opacity, I see.... What if I just use hexagonal, I'm not overly concerned by that simplification, could I get the alpha passed then? Or are the hexagons made to overlap also? Might have to get illustrator and do it in post-process

[nolabels.pdf](https://github.com/marcharper/python-ternary/files/5740576/nolabels.pdf)
[nolabels1.pdf](https://github.com/marcharper/python-ternary/files/5740577/nolabels1.pdf)

**Comment by DavidRRice** [comment]
Upon some experimentation with illustrator, I have found that overlaying heatmaps is actually a fairly awful idea. You lose most meaning of the colors. Thanks @marcharper for thinking about it.
