### ISSUE TITLE
Fill color of Ternary

### ISSUE THREAD

**Issue by dylanradovic** [marcharper/python-ternary#162]
Is there a way to fill a ternary scatter or plot with a single color? Cannot seem to find a way to do so. Thanks in advance!

**Comment by marcharper** [comment]
You can specify the same color for every (i, j, k) tuple? Or did you have something else in mind?

**Comment by dylanradovic** [comment]
![image](https://user-images.githubusercontent.com/57756023/107831697-82d27880-6d43-11eb-8d94-7c35fb8d4cc9.png)

I meant fill in the entire plot with a single background color. Take for example this ternary plot above with a light yellow background

**Comment by marcharper** [comment]
It shouldn't take long unless you are rendering a huge number of triangles. 

A workaround would be to use `matplotlib` to manually draw a single triangle behind the entire plot with the desired color. That would be a polygon with the points `(scale, 0, 0)`, `(0, scale, 0)`, and `(0, 0, scale)` projected onto the plane (`ternary` has helper functions to project), with a `zorder` smaller than your main diagram, and the desired `fillcolor`.

**Comment by dylanradovic** [comment]
got it! the second suggestion worked great. for ref used `plt.Polygon` to create a triangle
