### ISSUE TITLE
Could I plot a triangle plot where perpendicular as the coordinate axis.

### ISSUE THREAD

**Issue by Ritchiegit** [marcharper/python-ternary#168]
I want to draw a graph in which each category is a vertex, and the higher the confidence of belonging to that category, the closer it is to the vertex. I guess this requires setting high as the confidence level.
How should I use this library to complete this picture?
[picture link](https://ibb.co/HCFgXTP)

**Comment by marcharper** [comment]
Hi, I can't see your image (my firewall blocks the domain). But IIUC, you want to split your confidence over the possible classes and simply plot the points as those three confidences. If confidence is high in one of the classes, the point will show up near a vertex. If you have a lot of points, use a heatmap instead.

**Comment by Ritchiegit** [comment]
Wow, I think it might be difficult for me to plot it quantitatively. I will try to plot the points as those three confidences approximately. Thanks for your advice!
