### ISSUE TITLE
Ternary plot by reading data from a file with four columns

### ISSUE THREAD

**Issue by Masoom02** [marcharper/python-ternary#169]
If you compile this (attached sample data file), you get ternary plot with colorbar but no points on it. Could you direct me where I am going wrong! 

`
import ternary
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['figure.dpi'] = 200
matplotlib.rcParams['figure.figsize'] = (1,1)
figure, tax = ternary.figure(scale=1.0)
figure.set_size_inches(10,8)

tax.ticks(axis='lbr', multiple=0.2, linewidth=1, tick_formats="%.1f", offset=0.02)
tax.boundary()
tax.set_title("Plotting of sample trajectory datadata", fontsize=10)
# Load some data, tuples (x,y,z)
points = []
with open("share_data.txt") as handle:
    for line in handle:
        points.append(list(map(float, line.split('  '))))  
SCALE=1     
# Plot the data
#tax.plot_colored_trajectory(points, linewidth=2.0)
#
## Shuffle points for additional plot
#points = [(x, y, z,i) for (i,x, y, z) in points]
d = dict()
for c, x, y, z in points:
 d[(x,y,z)]=c   

#print ("Dict: {}".format(d.items())) 
tax.heatmap(d, scale = float(SCALE),style="triangular", cmap=plt.cm.get_cmap('YlOrRd'))
axes_colors = {'b': 'g', 'l': 'r', 'r': 'b'}
tax.boundary(linewidth=2.0, axes_colors=axes_colors)

tax.left_axis_label("$x_1$", offset=0.16, color=axes_colors['l'])
tax.right_axis_label("$x_0$", offset=0.16, color=axes_colors['r'])

tax.bottom_axis_label("$x_2$", offset=0.06, color=axes_colors['b'])

tax.gridlines(multiple=1, linewidth=2,
              horizontal_kwargs={'color': axes_colors['b']},
              left_kwargs={'color': axes_colors['l']},
              right_kwargs={'color': axes_colors['r']},
              alpha=0.7)
ticks = [i / float(SCALE) for i in range(SCALE + 1)]
tax.ticks(ticks=ticks, axis='rlb', linewidth=1, clockwise=True,
          axes_colors=axes_colors, offset=0.03, tick_formats="%0.1f")

tax.clear_matplotlib_ticks()
tax.show()`
[share_data.txt](https://github.com/marcharper/python-ternary/files/6371729/share_data.txt)

**Comment by marcharper** [comment]
The heatmap function doesn't interpolate the data for you; it only plots the data. See here: https://github.com/marcharper/python-ternary/issues/81
