### ISSUE TITLE
heatmap not show data

### ISSUE THREAD

**Issue by DS-Wen** [marcharper/python-ternary#170]
Hi, thank you for the powerful software! 
I was trying to plot ternary heatmap but somehow it didn't show the data like it was supposed to. 
For the following image, I used 
```tax = heatmap(data,style='h')```
![image](https://user-images.githubusercontent.com/33857502/116635637-e0b14c80-a991-11eb-8c40-473b826e5ab3.png)
The hexagons were not connected to adjacent points. If I use triangles, the data wasn't shown. 
So I was thinking if my data points were not dense enough, the spacing was 5 between points. 

When I used denser data points, (point spacing = 1), the heatmap was shown. This time both 'hexagonal' and 'triangular' worked. 
![image](https://user-images.githubusercontent.com/33857502/116635904-8e246000-a992-11eb-9324-4465a4aaf9cc.png)
Any ideas?

Thanks in advance

**Comment by marcharper** [comment]
It's impossible to say for sure without seeing the data, but my guess is that you expected the library to interpolate the data for you, which is does not.

**Comment by DS-Wen** [comment]
Thank you for your reply. 
I see. I was trying to understand how heatmap works. It seems to me that it draws polygons and filled the polygons with colors according to the height-values at the vertices. I if understand correctly, the "triangular" style in README, the color of the left-corner triangle is defined by point 0-1-4. 
![](https://github.com/marcharper/python-ternary/blob/master/readme_images/heatmap_styles_cubehelix.png)

For my plot, the colors of the triangles were somehow not filled because the points were far away.
My question is, say the first triangle to be colored, must the spacing between the vertices be 1? 

Here are two sets of data I used if you could take a look. 

Thank you very much. 
 [p1.csv](https://github.com/marcharper/python-ternary/files/6411601/p1.csv) 
[p2.csv](https://github.com/marcharper/python-ternary/files/6411603/p2.csv)

**Comment by marcharper** [comment]
The coordinates have to be integers and they must all sum to the same value `scale`. So a point with `x + y + z = scale` would be supplied in a dictionary as `d[(x, y)] = color_value`.

**Comment by DS-Wen** [comment]
Yes, that's what I did. 
For the first set of coordinates that didn't draw the heatmap, it is just a truncated set of the second set. 
All the X and Y sum up to 100. 
It's confusing me that why the second set worked but the first did not. 
The only difference between the two heatmap dictionaries are just the number of points. 

This are the x,y,z for the first set. With these points I generated a dictionary and assigned values to them. 
```
(0.0,0.0,100.0)
(0.0,5.0,95.0)
(0.0,10.0,90.0)
(0.0,15.0,85.0)
(0.0,20.0,80.0)
...
(90.0,5.0,5.0)
(90.0,10.0,0.0)
(95.0,0.0,5.0)
(95.0,5.0,0.0)
(100.0,0.0,0.0)
```

And this is the second set:
```
(0.0,0.0,100.0)
(0.0,1.0,99.0)
(0.0,2.0,98.0)
(0.0,3.0,97.0)
(0.0,4.0,96.0)
...
(98.0,1.0,1.0)
(98.0,2.0,0.0)
(99.0,0.0,1.0)
(99.0,1.0,0.0)
(100.0,0.0,0.0)
```

**Comment by marcharper** [comment]
The `heatmap` function expects data for each point. So in the top plot, the hexagons corresponding to the supplied points are plotted, and the surrounding hexagons are blank since you didn't supply data for those points.

As I said above, the library does not interpolate the data, it only plots it. The `heatmap` function doesn't know what to do with unspecified points -- you might want them blank, to indicate a lack of data, or you might want them interpolated, with some unknown method.
