### ISSUE TITLE
ticks below 1 are automatically displayed as "0"

### ISSUE THREAD

**Issue by joonas-si** [marcharper/python-ternary#174]
Hey there,
I ran into an issue with my tick marks and wasn't able to find a solution.
The ticks start at 0 and go up to 1 in 0.1 steps. When I display the plot all ticks below 1 are displayed as 0 (as you can see below).
I tried different codes to find a solution for this issue, like defining the tickmarks manually, but nothing worked.
I would appreciate your help!
![image](https://user-images.githubusercontent.com/77846586/120832777-51cfbb00-c561-11eb-8949-462b6cdb4252.png)

```
import matplotlib.pyplot as plt
import ternary
import numpy as np

figure, tax = ternary.figure(scale = 1)
figure.set_size_inches(10,10)
tax.set_title('title', fontsize=fontsize)
tax.left_axis_label('Left label', fontsize=fontsize)
tax.right_axis_label('Right label', fontsize=fontsize)
tax.bottom_axis_label('Bottom label', fontsize=fontsize)

tax.boundary(linewidth=2.0)
tax.gridlines(multiple=0.1, color='grey')

tax.plot( ((0.1,0.8,0.1),(0.8,0.1,0.1)) )

ticks = np.linspace(0,1,10)
tax.ticks(axis='rlb',multiple=0.1,axes_colors={'l': 'g', 'r':'b', 'b': 'r'},clockwise=False,label=ticks)
tax.get_axes().axis('off')

tax.get_axes().set_aspect(1)
```

**Comment by marcharper** [comment]
See #79
