### ISSUE TITLE
Question on ternary heatmap plot 

### ISSUE THREAD

**Issue by vanessaarango** [marcharper/python-ternary#189]
'''I am trying to run the following code inspired in yours for a ternary heatmap plot with cmap viridiris and I am getting TypeError: 'dict' object is not callable'''

i = [1, 0.7, 0.5, 0.3, 0, 0.7, 0.5, 0.3, 0.4, 0.3, 0.3, 0]
j =  [0, 0.3, 0.5, 0.7, 1, 0, 0 , 0, 0.3, 0.3, 0.4, 0.7]
k = [0, 0, 0, 0, 0, 0.3, 0.5, 0.7, 0.3, 0.4, 0.3, 0.3]
Loss_to_graph = Loss_new[0:12]

data_dictionary = {}
def dic_of_data(i,j,k,data):
        for a in range(0,len(Loss_to_graph)):
            # keys = (i[a], j[a], k[a])
            # values = Loss_to_graph[a]
            data_dictionary = dict(zip((i[a], j[a], k[a]), Loss_to_graph[a]))
    
print(data_dictionary)

figure, tax = ternary.figure(scale=scale)
tax.heatmapf(data_dictionary,scale = 1,cmap='viridis', style="triangular",boundary=True)
tax.ticks(axis='lbr', multiple=.1, linewidth=1, offset=0.025, tick_formats="%.1f")
tax.get_axes().axis('off')
tax.clear_matplotlib_ticks()
tax.show()

'''TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15524/1436728995.py in <module>
     14 
     15 figure, tax = ternary.figure(scale=scale)
---> 16 tax.heatmapf(data_dictionary,scale = 1,cmap='viridis', style="triangular",boundary=True)
     17 tax.ticks(axis='lbr', multiple=.1, linewidth=1, offset=0.025, tick_formats="%.1f")
     18 tax.get_axes().axis('off')

~\anaconda3\lib\site-packages\ternary\ternary_axes_subplot.py in heatmapf(self, func, scale, cmap, boundary, style, colorbar, scientific, vmin, vmax, cbarlabel, cb_kwargs)
    459         permutation = self._permutation
    460         ax = self.get_axes()
--> 461         heatmapping.heatmapf(func, scale, cmap=cmap, style=style,
    462                              boundary=boundary, ax=ax, scientific=scientific,
    463                              colorbar=colorbar, permutation=permutation,

~\anaconda3\lib\site-packages\ternary\heatmapping.py in heatmapf(func, scale, boundary, cmap, ax, scientific, style, colorbar, permutation, vmin, vmax, cbarlabel, cb_kwargs)
    315     data = dict()
    316     for i, j, k in simplex_iterator(scale=scale, boundary=boundary):
--> 317         data[(i, j)] = func(normalize([i, j, k]))
    318     # Pass everything to the heatmapper
    319     ax = heatmap(data, scale, cmap=cmap, ax=ax, style=style,

TypeError: 'dict' object is not callable'''

**Comment by bmondal94** [comment]
Your 'data_dictionary' is a dictionary not a function. 'heatmapf' needs a function. Replace '''tax.heatmapf(data_dictionary,scale = 1,cmap='viridis', style="triangular",boundary=True)''' with '''tax.heatmap(data_dictionary,cmap='viridis')'''.
