### ISSUE TITLE
Can not set the limits of each axis?

### ISSUE THREAD

**Issue by TraceMeGroup** [marcharper/python-ternary#190]
The range of the axis seems to start at 0, and each axis must have the same range ?

**Comment by bmondal94** [comment]
import ternary
import numpy as np

i = [1, 0.7, 0.5, 0.3, 0, 0.7, 0.5, 0.3, 0.4, 0.3, 0.3, 0]
j = [0, 0.3, 0.5, 0.7, 1, 0, 0 , 0, 0.3, 0.3, 0.4, 0.7]
k = [0, 0, 0, 0, 0, 0.3, 0.5, 0.7, 0.3, 0.4, 0.3, 0.3]
Z = np.linspace(0,1,12)
   
data_dictionary2 = {(i[a], j[a], k[a]) for a in range(len(Z))}

#------------------------ Original plot ---------------------------------------
figure, tax = ternary.figure(scale=1)
tax.scatter(data_dictionary2)
tax.ticks(axis='lbr', multiple=.1, linewidth=1, offset=0.025, tick_formats="%.1f")
tax.get_axes().axis('off')
tax.clear_matplotlib_ticks()
tax.set_title('Original')
tax.show()

#--------------- Setting axis limit in ternary axis ---------------------------
figure, tax = ternary.figure(scale=1)

#-- set axis limit
tax.set_axis_limits(axis_limits={'b':[0.3,0.7],'l':[0,1],'r':[0,1]}) 
#-- convert the data according to new coordinate
pp = tax.convert_coordinates(data_dictionary2)

tax.scatter(pp)

#-- Update the axis ticks
tax.get_ticks_from_axis_limits(multiple=0.1)
tax.set_custom_ticks(multiple=.1, linewidth=1, offset=0.025, tick_formats="%.1f")

tax.get_axes().axis('off')
tax.clear_matplotlib_ticks()
tax.set_title("Set axes limits")
tax.show()

#--------------- Setting axis limit in matplotlib axis ------------------------
figure, tax = ternary.figure(scale=1)
ax = tax.get_axes()
ax.set_xlim(0.3,0.7)
tax.scatter(data_dictionary2)
tax.ticks(axis='lbr', multiple=.1, linewidth=1, offset=0.025, tick_formats="%.1f")
tax.get_axes().axis('off')
tax.clear_matplotlib_ticks()
tax.set_title("Zoom axes limits")
tax.show()
