### ISSUE TITLE
Problem in making the ternary heatmap if the key interval is not 1. 

### ISSUE THREAD

**Issue by rudraavishek** [marcharper/python-ternary#193]
I have a dictionary that looks like this (a truncated version):

{(0.0, 100.0, 0.0): 0.09487584912554602,
 (0.0, 95.2381, 4.7619): 0.09786287021465875,
 (0.0, 90.47619999999999, 9.523810000000001): 0.10049247391912094,
 (0.0, 85.7143, 14.285700000000002): 0.10284007966168865,
 (0.0, 80.9524, 19.0476): 0.10495662627269356,
 (0.0, 76.1905, 23.8095): 0.10687895915154863}

Where the  interval in the keys is 4.762 instead of 1. I have trouble making a heatmap for this data. Any help is appreciated.

**Comment by marcharper** [comment]
Hi, do you mean the data is in units/multiples of 4.762? The easiest solution would be just to scale the data to the integer multiple before plotting. You can overwrite the axis labels if desired.
