### ISSUE TITLE
How to plot the Ternary Choropleth Map?

### ISSUE THREAD

**Issue by RihuiAn** [marcharper/python-ternary#195]
How can I get the color of the points to plot the Ternary Choropleth Map like "tricolore" in R (https://github.com/jschoeley/tricolore)?

**Comment by marcharper** [comment]
In that example ggplot is making the choropleth. You'd have to similarly find another library to do that in Python.

**Comment by RihuiAn** [comment]
Do you know which library in Python can help me make the choropleth map like ggplot?

**Comment by marcharper** [comment]
I don't have a recommendation
