### ISSUE TITLE
Custom Axis Directions

### ISSUE THREAD

**Issue by AndrewFalkowski** [marcharper/python-ternary#200]
Looking to replicate a non-standard ternary plot where the left and bottom axis increase from the bottom left corner ([example](https://blog.kakaocdn.net/dn/GwQkV/btrouyNmW6e/Lr8QGNDaFl8Pj7CMXvw35k/img.jpg)). This structure is fairly standard in my field, but I haven't found a single ternary plotting library capable of replicating it. Wondering if there is some way to define custom axis directions in your library?

Thanks!

**Comment by bmondal94** [comment]
Dear [AndrewFalkowski](https://github.com/AndrewFalkowski),
Nice. Yes, it is certainly possible. If I understood correctly, your example plot is the triangular version of 
![Rectangular_ternary_plot svg](https://user-images.githubusercontent.com/56228126/196195803-1b5f551d-6f46-4c04-8617-f4d87a1df2df.png)
If this is the case, then you can use the ```python-ternary``` to plot the data points. The only thing you have to care about is how to read those data and accordingly the axis ticks. Below is a test example.
```
import ternary, random
import matplotlib.pyplot as plt

points = [(10,10,80),(40,20,40)]
### Scatter Plot
scale = 100
axes_colors={'b':'r','l':'b','r':'k'}

figure, ax = plt.subplots(figsize=(10,10))
tax = ternary.TernaryAxesSubplot(ax=ax,scale=scale)

tax.set_title("Scatter Plot", fontsize=20)
tax.boundary(linewidth=2.0, axes_colors=axes_colors)
tax.gridlines(multiple=5, left_kwargs={'c': axes_colors['l']}, right_kwargs={'c': axes_colors['r']}, horizontal_kwargs={'c':  axes_colors['b']},linewidth=1)

tax.scatter(points, marker='s', color='red', label="test")

tax.legend()
tax.ticks(axis='l', linewidth=1, multiple=10, clockwise=True, axes_colors={'l':'r'})
tax.ticks(axis='b', linewidth=1, multiple=10, clockwise=False, axes_colors={'b':'b'})
tax.ticks(axis='b', linewidth=1, multiple=10, clockwise=True, axes_colors={'b':'k'})

tax.get_axes().axis('off')
tax.clear_matplotlib_ticks()
tax.get_axes().set_aspect(1)

tax.show()
```
![test_ternary_non_std](https://user-images.githubusercontent.com/56228126/196202506-49bdfa72-2c07-4dfc-894c-9b5f25cc5ed3.png)

This is what it looks like. The example is very preliminary.

**Comment by AndrewFalkowski** [comment]
Thank you, this was helpful.
