### ISSUE TITLE
Can't find a way that works to reduce label overlap.

### ISSUE THREAD

**Issue by GlacialGeo** [marcharper/python-ternary#205]
Perhaps it's just my own limitations, but the ternary library doesn't seem to provide an easy way to adjust label placement to avoid overlaps. I tried using adjustText, but without success (I get an annotation error). Here is an example (attached) where you see some label overlap. It would just be useful sometimes to be able to add the labels next to data points and position them better.   
![Picture1](https://user-images.githubusercontent.com/39131031/235780553-83e52917-bd1d-4409-b328-9a940cc870aa.png)

**Comment by marcharper** [comment]
If you are using the annotate function, you can pass through [arguments that matplotlib](https://matplotlib.org/stable/tutorials/text/annotations.html#plotting-guide-annotation) expects, which should allow you to move the labels around.

**Comment by GlacialGeo** [comment]
Thanks. Yes, I have been able to place the labels relative to the data points, move them around, add some offset, etc. I just couldn't find a way for the positioning to automatically consider, for each label, the other labels nearby to avoid overlap. I thought the "adjustText" library would do it, but I couldn't make it work on this graph. That's ok. I can reduce the length of text to the bare min and move the shorter labels around until overlap is minimized. Thanks again.
