### ISSUE TITLE
Plotting heatmap from scatter plot

### ISSUE THREAD

**Issue by Lorenzo128** [marcharper/python-ternary#212]
Hi! 

I would like to create an heatmap from the scatter density within each triangle. 
If I understand correctly the ternary.heatmap function aggregates and averages the values from the corner of each triangle. 

Is there any way to plot such an heatmap with this library?

Thanks a lot in advance! 

Best
Lorenzo

![Screenshot 2024-07-01 alle 17 19 05](https://github.com/marcharper/python-ternary/assets/44572432/3f2c79ed-2ca2-4079-b1fe-696a7548f8c1)

**Comment by marcharper** [comment]
No, you have to compute the heatmap colors/values yourself. There are some other issues describing how to manually do this like #81
