### ISSUE TITLE
RGB heatmap with triangle vertices=R,G,B

### ISSUE THREAD

**Issue by CarlosGrohmann** [marcharper/python-ternary#213]
I'm following the example of the RGBA heatmap. 

I'd like to know how to get the triangle vertices to be red, green, blue. In the example, they are magenta, yellow, cyan.

In the example we have this function: 

```
def generate_heatmap_data(scale=5):
    from ternary.helpers import simplex_iterator
    d = dict()
    for (i, j, k) in simplex_iterator(scale):
        d[(i, j, k)] = color_point(i, j, k, scale)
    return d
```

If I set the scale to 1 and print the dictionaries, I get this:
```

{(0, 0, 1): (1.0, 1.0, 0.0, 1.0)}
{(0, 0, 1): (1.0, 1.0, 0.0, 1.0), (0, 1, 0): (0.0, 1.0, 1.0, 1.0)}
{(0, 0, 1): (1.0, 1.0, 0.0, 1.0), (0, 1, 0): (0.0, 1.0, 1.0, 1.0), (1, 0, 0): (1.0, 0.0, 1.0, 1.0)}
```

So we see that all dicts have two colors set to 1.0 and one color set to 0.0, hence the magenta, yellow, cyan.

Any way to get these as red, green, blue? That is, each dict would have one color set to 1.0 and two colors set to 0.0

thanks

**Comment by bmondal94** [comment]
You can adjust the `color_point()` function definition in that example according to your need. For e.g., you can use the following `color_point()` function to get red, green, and blue corners.
```
def color_point(x, y, z, scale):
    r = x / scale
    g = y / scale
    b = z / scale
    return (r, g, b, 1.)
```

**Comment by CarlosGrohmann** [comment]
Excellent, thank you!
