### ISSUE TITLE
python 3.k ipython 4.1 import error

### ISSUE THREAD

**Issue by mmngreco** [marcharper/python-ternary#23]
When I try import the packege get this import error: 

```python
import ternary

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fe0219fb98b4> in <module>()
      3 import matplotlib.pyplot as plt
      4 import seaborn as sns
----> 5 import ternary

/Users/mmngreco/anaconda/envs/py3/lib/python3.4/site-packages/python_ternary-0.0.1-py3.4.egg/ternary/__init__.py in <module>()
----> 1 from plotting import (
      2     clear_matplotlib_ticks,
      3     plot,
      4     resize_drawing_canvas,
      5     scatter,

ImportError: No module named 'plotting'
```

Version:  
3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41) 
[GCC 4.2.1 (Apple Inc. build 5577)]

**Comment by marcharper** [comment]
Thanks for the bug report. I just pushed a commit to master to address python3 importing and a few other 2to3 issues. Can you please test this on your machine? I tested on 2.7.9 and 3.4.3 (the latest ubuntu packages).

**Comment by mmngreco** [comment]
Thanks, now imports correctly. :-)

__Version:__
Ipython 4.0.0
Python 3.5.0 (default, Sep 23 2015, 04:41:38)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)
