### ISSUE TITLE
python3.5 ipython4 ternary.figure error

### ISSUE THREAD

**Issue by mmngreco** [marcharper/python-ternary#27]
I try implement the example of your README.md but I get this tracebak:

```python
from matplotlib import pyplot
import ternary

## Boundary and Gridlines
scale = 40
figure, tax = ternary.figure(scale=scale)

# Draw Boundary and Gridlines
tax.boundary(color="black", linewidth=2.0)
tax.gridlines(color="blue", multiple=5) # Every 5th gridline, can be a float

# Set Axis labels and Title
fontsize = 20
tax.set_title("Simplex Boundary and Gridlines", fontsize=fontsize)
tax.left_axis_label("Left label $\\alpha^2$", fontsize=fontsize)
tax.right_axis_label("Right label $\\beta^2$", fontsize=fontsize)
tax.bottom_axis_label("Bottom label $\\Gamma - \\Omega$", fontsize=fontsize)

# Set ticks
ternary_ax.ticks(axis='lbr', color="black", linewidth=1)

# Remove default Matplotlib Axes
tax.clear_matplotlib_ticks()

pyplot.show()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-081775008589> in <module>()
      4 ## Boundary and Gridlines
      5 scale = 40
----> 6 figure, tax = ternary.figure(scale=scale)
      7 
      8 # Draw Boundary and Gridlines

AttributeError: module 'ternary' has no attribute 'figure'
```

**Comment by marcharper** [comment]
Ok, a `map(...)` needed to be `list(map(...))` for python 3 (in the data loading function of examples). All the examples run in python 3.4 now.

**Comment by marcharper** [comment]
I'm not sure why you got the error that you did, this doesn't happen for me::
```
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ternary
>>> ternary.figure()
(<matplotlib.figure.Figure object at 0x7f86d03c2dd8>, TernaryAxesSubplot: -9223363273295329441)
>>> 
```

If you still have this issue please let me know!

**Comment by mmngreco** [comment]
I try again with the same result. so I after that, try **re-install** the package and now works correctly! :-)
Thanks!

**Comment by marcharper** [comment]
Great, thanks for opening the issue.

**Comment by sshojiro** [comment]
I have encountered the same issue, even after re-install of the package via `pip`. 
Could anyone help me? Thank you in advance.

```python
$ python -c 'import ternary; ternary.figure()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'ternary' has no attribute 'figure'
```

## Version Info.

- python: Python 3.6.6 :: Anaconda, Inc.
- python-ternary: 1.0.6

**Comment by sshojiro** [comment]
I fixed the issue manually: I downloaded the repo to my local machine and copy the `ternary/` directory to my workplace.

As long as I see, the package via `pip` or `conda` does not work right now. You should check what is happening on.

**Comment by mmngreco** [comment]
> I have encountered the same issue, even after re-install of the package via `pip`.
> Could anyone help me? Thank you in advance.

I couldn't replicate the problem, it works well for me. What I did:

1. create new environment: `conda create -n tst python=3.6`
1. activate the environment: `conda activate tst`
1. install from pip: `pip install python-ternary`
1. test: `python -c 'import ternary; ternary.figure()'`

my environemtent at the end:

```bash
$ python -s -m pip freeze
certifi==2019.9.11
cycler==0.10.0
kiwisolver==1.1.0
matplotlib==3.1.1
numpy==1.17.2
python-dateutil==2.8.0
python-ternary==1.0.6
```

Options to take into account when you reinstalls packages:

```bash
# pip's way
pip install python-ternary --force-reinstall --no-cache-dir
```

**Comment by marcharper** [comment]
Thanks @mmngreco ! Let's us know if you still have issues, @sshojiro .
