### ISSUE TITLE
Scatterplot over Heatmap

### ISSUE THREAD

**Issue by nathanbreitsch** [marcharper/python-ternary#32]
Is it possible to put a scatterplot over a heatmap?  Whenever I try, the heatmap covers the points.  Is there some way to control what ends up on top?

**Comment by marcharper** [comment]
I'm sure there is -- probably a matplotlib option that you can passthrough that sets the object depth. I'll look into it.

**Comment by marcharper** [comment]
Looks like you can set `zorder`: see the [examples here](http://matplotlib.org/examples/pylab_examples/zorder_demo.html]. Let me know whether it works for you, the library could set the heatmaps to have a lower zorder by default.

**Comment by nathanbreitsch** [comment]
Yes, this works:

```python
ax.scatter(coordinates, color="black", marker="o", zorder=2)    
```
Thank You!

**Comment by marcharper** [comment]
Great. If you make a nice diagram and would like to contribute to the examples, let me know!
