### ISSUE TITLE
Code crashes when drawing axes

### ISSUE THREAD

**Issue by jamesafoster** [marcharper/python-ternary#41]
Here is the traceback. The outer function is just a wrapper of mine, and doesn't set the axes colors.

    TypeError                                 Traceback (most recent call last)
<ipython-input-11-465709352694> in <module>()
      2 figure, tax = ternary.figure( scale=scale )
      3 
----> 4 plotPreferences( tax, 'Sig', players, [4], [0,1,2,3,4,5] )

<ipython-input-8-c3ef420fca9f> in plotPreferences(tax, agentType, agent, runList, inputList, colors)
     12     tax.bottom_axis_label("Preference for 2", fontsize=fontsize)
     13 
---> 14     tax.boundary(color="black", linewidth=2.0)
     15     tax.gridlines(multiple=0.1, color="blue")
     16     tax.ticks(axis='lbr', color="black", linewidth=1, multiple=0.1)

C:\Users\Peter\Anaconda3\lib\site-packages\ternary\ternary_axes_subplot.py in boundary(self, scale, axes_colors, **kwargs)
    201         ax = self.get_axes()
    202         self.resize_drawing_canvas(scale)
--> 203         lines.boundary(scale=scale, ax=ax, axes_colors=axes_colors, **kwargs)
    204 
    205     def gridlines(self, multiple=None, horizontal_kwargs=None, left_kwargs=None,

C:\Users\Peter\Anaconda3\lib\site-packages\ternary\lines.py in boundary(ax, scale, axes_colors, **kwargs)
    119             axes_colors[_axis] = 'black'
    120 
--> 121     horizontal_line(ax, scale, 0, color=axes_colors['b'], **kwargs)
    122     left_parallel_line(ax, scale, 0, color=axes_colors['l'], **kwargs)
    123     right_parallel_line(ax, scale, 0, color=axes_colors['r'], **kwargs)

TypeError: horizontal_line() got multiple values for keyword argument 'color'

**Comment by marcharper** [comment]
When I merged in a PR to allow for the axes to be different colors, I changed the API for `boundary`. If you just want a black boundary, simply use `tax.boundary(linewidth=2.0)` now. Otherwise you can specify the colors like so:

```
axes_colors = {'b': 'g', 'l': 'r', 'r':'b'}
tax.boundary(linewidth=2.0, axes_colors=axes_colors)
```

It's just a dictionary with colors for the bottom `b`, left `l`, and right `r` axes.

**Comment by jamesafoster** [comment]
Thanks, Marc!

j

~~~~~~~~~~~~~~~~~~~~~~~~~~~
James A. Foster
Professor, University of Idaho
Institute for Bioinformatics & Evolutionary STudies (IBEST)

> On Mar 14, 2016, at 11:58 AM, Marc Harper <notifications@github.com> wrote:
> 
> When I merged in a PR to allow for the axes to be different colors, I changed the API for boundary. If you just want a black boundary, simply use tax.boundary(linewidth=2.0) now. Otherwise you can specify the colors like so:
> 
> axes_colors = {'b': 'g', 'l': 'r', 'r':'b'}
> tax.boundary(linewidth=2.0, axes_colors=axes_colors)
> It's just a dictionary with colors for the bottom b, left l, and right r axes.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/marcharper/python-ternary/issues/41#issuecomment-196472684>.
>
