### ISSUE TITLE
Different range for three axes

### ISSUE THREAD

**Issue by buptxz** [marcharper/python-ternary#47]
I need to plot ternary figure with different range in three axes. I am not sure it is a common need in this kind of figure. If it is, maybe we can add this feature.

![ternary](https://cloud.githubusercontent.com/assets/9117561/14752760/273b962c-089f-11e6-9674-062b50a1964b.JPG)

**Comment by marcharper** [comment]
You can actually do this now by scaling your data and supplying custom tickmarks. There's just not a convenience function for this feature. If you want to put a PR together for it please go ahead, otherwise I'll see what I can do eventually. (There are higher priority features.)

**Comment by buptxz** [comment]
Thank you. That's a way to do it I never thought. 
I will try if I can do it.

**Comment by marcharper** [comment]
Thanks to @tgwoodcock for adding this feature!
