### ISSUE TITLE
Spotty Compatibility with Python 2.7

### ISSUE THREAD

**Issue by skyler14** [marcharper/python-ternary#48]
Running first sample snippet crashes:

Traceback (most recent call last):
  File "monte/ternar-traj.py", line 13, in <module>
    ternary_ax.gridlines(color="black", multiple=0.2)
NameError: name 'ternary_ax' is not defined

Running second snippet generates plot, but out of all the lines only the green line renders, and the axis labels disappear.

**Comment by marcharper** [comment]
Thanks for posting an issue. I've fixed the example in the readme: `ternary_ax` should have been `tax` and that is why you did not see the colored grid-lines.

As for the labels, some mac users have reported this issue (#36) and found a workaround; I have not been able to reproduce it on any other system. On my system the examples in [examples.py](https://github.com/marcharper/python-ternary/blob/master/examples.py) (very similar to those in the readme) all work fine on both Python 2.7 and 3.4/5, as do the examples in the [Jupyter notebook](https://github.com/marcharper/python-ternary/blob/master/Ternary-Examples.ipynb).

Simply saying that the compatibility with Python 2.7 is "spotty" is neither accurate nor helpful. To reproduce your issue I'll need to know, at the least:
* Your OS
* Your version of matplotlib
* Your version of ternary
* The code that is not performing as expected.

If the workaround above doesn't work for you, feel free to reopen the issue with the above information.

**Comment by skyler14** [comment]
Hi Marc, I ran through the example files you had and they all worked fine. The chart in the example file also renders perfectly too. Thanks for the quick response.
