### ISSUE TITLE
Box around plot

### ISSUE THREAD

**Issue by merritjm** [marcharper/python-ternary#49]
Hello, 
I've tried to follow your examples to make a ternary plot with some success. However when i create a plot with some long or large font axis labels, a box surrounding the plot does not resize and cuts through the labels.  Is there a specific option which is controlling this box size or rescaling it?
I've appended the code and a copy of the figure.
I'm using matplotlib v1.5.1 and python 2.7
Thanks in advance,
Jeremy

![fig](https://cloud.githubusercontent.com/assets/19717445/15759678/c3f1b10a-28dd-11e6-87b1-2d854c0e27cf.png)

import matplotlib
from matplotlib import pyplot, gridspec
import ternary

line = [[.1,.2,.7],[.5,.1,.4]]
### Plot Various lines
scale = 1
figure, ternary_ax = ternary.figure(scale=scale)

# Draw Boundary and Gridlines
ternary_ax.boundary(linewidth=2.0)
ternary_ax.gridlines(color="blue", multiple=0.1)
   
# Set Axis labels and Title
fontsize = 20
ternary_ax.set_title("Long title", fontsize=20)
ternary_ax.left_axis_label("longer title...", fontsize=fontsize, offset=0.2)
ternary_ax.right_axis_label("blah blah blah", fontsize=fontsize, offset=0.2)
ternary_ax.bottom_axis_label("more stuff here", fontsize=fontsize, offset=-0.2)   
ternary_ax.plot(line, linewidth=2.0, label="line")
ternary_ax.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.2)    
ternary_ax.clear_matplotlib_ticks()
ternary_ax.ticks(axis='lbr', multiple=0.1, linewidth=1, offset=0.03)
ternary_ax.show()

**Comment by marcharper** [comment]
Hi @merritjm, the box is matplotlib's default plot box. You should be able to remove it completely if you follow the examples [here](http://stackoverflow.com/questions/14908576/how-to-remove-frame-from-matplotlib-pyplot-figure-vs-matplotlib-figure-frame).

Currently I'm not sure how to compute the extent of the labels to adjust the box automatically. But I'm sure you can direct matplotlib to make it larger if you still want it.
