### ISSUE TITLE
axis order confution

### ISSUE THREAD

**Issue by MartinHvidberg** [marcharper/python-ternary#50]
Thanks for a cool project...

I was fooling around with the possibilities, because I needed a quick ternary poly, and my R have become rusty...
More specifically I tried the following minimalistic code:

```
from matplotlib import pyplot

import ternary

if __name__ == '__main__':
    
    scale = 100
    fontsize = 10
    col_axis = {'b': 'g', 'l': 'r', 'r':'b'}
    
    figure, tax = ternary.figure(scale=scale)
    figure.set_size_inches(10, 10)
    tax.clear_matplotlib_ticks()
    
    tax.set_title("mini tern", fontsize=20)
    
    tax.boundary(linewidth=1.0)
    tax.bottom_axis_label("X-axis", fontsize=fontsize, color=col_axis['b'])
    tax.right_axis_label("Y-axis", fontsize=fontsize, color=col_axis['r'])
    tax.left_axis_label("Z-axis", fontsize=fontsize, color=col_axis['l'])
    
    tax.gridlines(multiple=10, linewidth=2,
              horizontal_kwargs={'color':col_axis['b']},
              left_kwargs={'color':col_axis['l']},
              right_kwargs={'color':col_axis['r']},
              alpha=0.7)
    
    lst_pnts = [[10,10,80],[20,60,20],[40,30,30]]
    tax.scatter(lst_pnts, marker='D', color='black')
    for pnt in lst_pnts:
        tax.annotate(str(pnt),pnt)

    pyplot.show()

```

I works in the sense that it produces a plot, and give no error messages.
But I can't say that I agree with the plot...
For any (x,y,z) coordinate I would the bottom (horizontal) axis to be x-axis, indexed from left to right, like in any classic 2D coordinate system.
I would then assume the right axis to be y-axis, indexed from bottom up. And finally the left axis to be z-axis, indexed top down, to complete the circle.

This seems to be perfect, when I try to read out the three points in my example [10,10,80],[20,60,20],[40,30,30]. And the green-blue-red colouring of the axis-lables follow the same standard.

But the colouring og the grid-lines seem to slant to the wrong side?

Can you please tell me if I'm doing this wrong, or maybe understanding the concept wrong.

Best regards
Martin Hvidberg
![figure_1](https://cloud.githubusercontent.com/assets/5923517/15836183/dadd431c-2c33-11e6-8169-e2e8b31873e1.png)

**Comment by marcharper** [comment]
Hi Martin,

There's actually more than one way to label the axes on a ternary plot and it can be confusing. In the readme there is a section "Axes Ticks and Orientations" that discusses this. An arbitrary choice has to be made and the library operates as follows by default.

The default is left to right on the x coordinate and then up-right on the up-right axis, with the value of the second coordinate given by the horizontal line that intersects the right axis.

If you would like the points plotted differently the best option is to simply permute the points as needed.

**Comment by MartinHvidberg** [comment]
Hi Marc

Thanks for your fast and good reply.

I'm not sure my question was clear enough. My problem is not with the
axis nor the labels, but the grid lines colour.

I'm busy with other work, the next few days. But I'll try to look into
your answer, any may risk to write you again later.

Best regards
Martin

On 2016-06-07 08:21, Marc Harper wrote:
> Hi Martin,
> 
> There's actually more than one way to label the axes on a ternary plot
> and it can be confusing. In the readme there is a section "Axes Ticks
> and Orientations" that discusses this. An arbitrary choice has to be
> made and the library operates as follows by default.
> 
> The default is left to right on the x coordinate and then up-right on
> the up-right axis, with the value of the second coordinate given by the
> horizontal line that intersects the right axis.
> 
> If you would like the points plotted differently the best option is to
> simply permute the points as needed.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/marcharper/python-ternary/issues/50#issuecomment-224190666>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFpivebEe0zGkQIkxxM-YOCuYc2byz1Pks5qJQ30gaJpZM4IvRoi>.
> 

-- 
" ... But this required the analysis of a two-dimensional surface, and
he chose to leave it while he first considered in detail some rather
simpler cases"

      - about Alan Thuring (1950)

**Comment by marcharper** [comment]
In this case your code is supplying the colors and you can easily change them by altering the `axes colors` dictionary. See the colors [reference list](http://matplotlib.org/api/colors_api.html). For example you can swap red and green using `col_axis = {'b': 'r', 'l': 'g', 'r':'b'}` instead of `col_axis = {'b': 'g', 'l': 'r', 'r':'b'}`.
