### ISSUE TITLE
The plot generated by `heatmap` is not equilateral

### ISSUE THREAD

**Issue by samuelandjw** [marcharper/python-ternary#51]
Here is the code I used to generate a ternary plot:

```
import ternary
scale = N

fig, ax = plt.subplots()
ax.axis("off")
figure, tax = ternary.figure(scale=scale, ax=ax)

tax.heatmap(heatmap_dict, cmap=None)

figure.set_size_inches(10, 10)

tax.boundary(linewidth=2.0)
tax.set_title("$W12$")

# Set ticks
tax.ticks(axis='lbr', linewidth=1, multiple=10)

# Remove default Matplotlib Axes
tax.clear_matplotlib_ticks()

tax.show()
```

where `heatmap_dict` is a dictionary mapping (i,j) to a value. See the figure below for the generated plot. Obviously the bottom side is shorter than either of the other two sides. I noticed that this feature is also present in the documentation of this package.

![produce_figures_ipynb_-_code_-____of3_code_](https://cloud.githubusercontent.com/assets/374391/16116633/a4a610ce-3400-11e6-92f4-851df42c051d.png)

**Comment by marcharper** [comment]
You just have to stretch the image after it is plotted by matplotlib. Just pull the pop window's corners until the shape is just right.

Depending on your installation settings, the image may or may not be exactly equilateral as displayed, but it is equilateral as drawn. The error bar takes up some space (which varies based on the ticks of the color bar, the font size, etc.) so it's up to you to properly stretch the image before saving.

If that doesn't work and you need a publication quality image, I recommend that you make the plot with and without the colorbar and use e.g. photoshop or gimp to add the color bar to the image that you are happier with.

**Comment by samuelandjw** [comment]
Manually stretching the image is certainly an option, but my biggest concern is whether the ticks automatically adjust to the stretching, i.e., whether the ticks are parallel to the corresponding side after stretching.

In my installation settings, the plot is still not equilateral even without the colorbar.

AFAIK, this does not happen to `heatmapf` nor another plotting functions.

**Comment by marcharper** [comment]
Did you try stretching it? The ticks and labels should move with the axes. The library is specifically programmed to do so for this reason. If that doesn't work please let me know.

FYI some of the images in the documentation were stretched manually. Unfortunately there is not an easy way to determine how much space the various text blocks will take up that I am aware of, which is why the plot isn't automatically resized. There are also local matplotlib options that dictate e.g. default image dimensions, so it's unlikely that the library's behaviors on this matter will change in the near future.

**Comment by samuelandjw** [comment]
I did not try stretching it because I mainly work with IPython notebook with inline image... good to know the ticks and labels will adjust. Also thanks for your elaboration on the issue!

**Comment by marcharper** [comment]
You are welcome. In case you haven't seen this before, you can set the default figure size in a notebook with:
```
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (10, 6) # inches width and height.
```
