### ISSUE TITLE
example_scatter_colorbar.py  on mac

### ISSUE THREAD

**Issue by csutton7** [marcharper/python-ternary#55]
Hello, 

I am getting this issue using example_scatter_colorbar.py on my mac with matplotlib version 1.5.1:

  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 856, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property colorbar

**Comment by marcharper** [comment]
Can you post the sample code? What version of the library are you using?

**Comment by csutton7** [comment]
Hi,

I just copied the code exactly from here: https://github.com/
marcharper/python-ternary/blob/master/examples/scatter_colorbar.py
and the txt file from ../sample_data/scatter_colorbar.txt

versions:

matplotlib==1.5.1

python-ternary==1.0

**Comment by marcharper** [comment]
Did you use pip to install? That example may only work on the latest master.

**Comment by csutton7** [comment]
Thanks, you're right. Now it works.
