### ISSUE TITLE
Minor issue in README.md: Simplex Boundary and Gridlines

### ISSUE THREAD

**Issue by joaoleal** [marcharper/python-ternary#56]
In the "Simplex Boundary and Gridlines" example in the README.md the last line reads
`ternary.plt.show()`
but it should be 
`tax.show()`

**Comment by marcharper** [comment]
They should both work.

**Comment by joaoleal** [comment]
Is it a new feature?
I installed python-ternary using pip in kubuntu 15.10.
That example gives me the following error:
Traceback (most recent call last):
  File "ternary-plot.py", line 41, in <module>
    ternary.plt.show()
AttributeError: 'module' object has no attribute 'plt'

**Comment by marcharper** [comment]
It's in the master but not the latest release on pip.
