### ISSUE TITLE
Minor issue. How do I turn the ternary plots ticks inwards? 

### ISSUE THREAD

**Issue by AnandoUS** [marcharper/python-ternary#58]
I wanted to know if there is a parameter in the ticks attribute tax.ticks(axis='lbr', linewidth=1, multiple=0.1), to give the direction of the ticks for the ternary plot. I was thinking something similar to tax.ax(axis = 'y', direction = 'in').

**Comment by marcharper** [comment]
Hi @AnandoUS, there's no parameter for this now, though you could modify the function that computes the tick marks to do this without too much effort.
