### ISSUE TITLE
markersize not recognised

### ISSUE THREAD

**Issue by zimshady** [marcharper/python-ternary#59]
When using `tax.scatter`, `markersize` cannot be specified in the arguments. The following error occurs:

> AttributeError: Unknown property markersize

**Comment by marcharper** [comment]
Can you give me a code sample? It looks like an error message from matplotlib so I need to see how you are calling the function.

**Comment by zimshady** [comment]
Herewith a minimum (almost) working example:   
    
    import ternary
    from matplotlib import *

    #got somedata here

    scale = 100
    figure, tax = ternary.figure(scale=scale)
    tax.set_title("Tectonic setting", fontsize=20)
    tax.boundary(linewidth=2.0)
    tax.gridlines(multiple=5, color="black")

    tax.scatter(somedata,marker='p',color='red', markersize=5)

    tax.show()

**Comment by marcharper** [comment]
This issue is that matplotlib's scatter doesn't accept markersize. This snippet gives the same error:
```
import matplotlib.pyplot as plt
plt.scatter([1, 2], [2, 1], markersize=1)
```

The correct kwarg is just `s=1`.

**Comment by zimshady** [comment]
Apologies! I should have checked that first.
