### ISSUE TITLE
New paper using Python-Ternary

### ISSUE THREAD

**Issue by btweinstein** [marcharper/python-ternary#63]
@marcharper A paper I just posted to the bioRxiv cites and uses Python-Ternary. Can you add these lines to the readme adding the citation? My own fork is hopelessly outdated. 

- [Genetic Drift and Selection in Many-Allele Range Expansions](http://biorxiv.org/content/early/2017/06/07/145631) by [Bryan T. Weinstein](https://github.com/btweinstein)

**Comment by marcharper** [comment]
Done! Thanks for letting me know :)

**Comment by btweinstein** [comment]
Hello again. Just in case you want to upload the figure from the paper using Python ternary, see the attached. I apologize, I should have attached this last night. 

![python_ternary_example](https://user-images.githubusercontent.com/5347518/26935738-b9d07540-4c3a-11e7-9160-c733e0b498a5.png)

**Comment by marcharper** [comment]
Thanks! I've added it with a link to the paper.
