### ISSUE TITLE
Labels miss in saved picture when not calling plt.show()

### ISSUE THREAD

**Issue by svrnwnsch** [marcharper/python-ternary#68]
If i try to save the plot from the tutorial the following way no labels are shown in the saved plot.

```
    import ternary

    ## Boundary and Gridlines
    scale = 40
    figure, tax = ternary.figure(scale=scale)

    # Draw Boundary and Gridlines
    tax.boundary(linewidth=2.0)
    tax.gridlines(color="black", multiple=5)
    tax.gridlines(color="blue", multiple=1, linewidth=0.5)

    # Set Axis labels and Title
    fontsize = 20
    tax.set_title("Simplex Boundary and Gridlines", fontsize=fontsize)
    tax.left_axis_label("Left label $\\alpha^2$", fontsize=fontsize)
    tax.right_axis_label("Right label $\\beta^2$", fontsize=fontsize)
    tax.bottom_axis_label("Bottom label $\\Gamma - \\Omega$", fontsize=fontsize)

    # Set ticks
    tax.ticks(axis='lbr', linewidth=1)

    # Remove default Matplotlib Axes
    tax.clear_matplotlib_ticks()
    tax.savefig("test.png")
    ternary.plt.show()
```

what fixes the problem is to save the picture after displaying it

```
    ternary.plt.show()
    tax.savefig("test.png")
```
The problem is that I am forced to call plt.show() to save the labels in my graph.
It should be not be necessary to call plt.show().

**Comment by marcharper** [comment]
Can you try calling `tax._redraw_labels()` directly before `savefig`?

If that doesn't work then I'll need to know your version of python, matplotlib, etc. Matplotlib should be calling `mpl_redraw_callback` before saving.

**Comment by svrnwnsch** [comment]
This fixed my problem. Maybe this call should be added when the `save()` function is called?

**Comment by marcharper** [comment]
@svrnwnsch That's probably a good idea. Want to open a PR?

**Comment by marcharper** [comment]
This is done.
