### ISSUE TITLE
Set vmax and vmin based on vertices_values

### ISSUE THREAD

**Issue by svrnwnsch** [marcharper/python-ternary#70]
If vmax or vmin is not given for the heatmap plot. In my opinion the value should represent the maximal and minimal plotted value instead of the maximal and minimal value of the given data.

This changes the plot if the triangular style is used. If just one data value is extremely high or low only a small range of the colorbar is used.

I could try to make a PR which fixes this behavior.

**Comment by marcharper** [comment]
I'm not sure I understand -- the averaging in the triangular method should tend to reduce the extreme values in the plotted set, and it should only affect the neighboring triangles. If you want the exact values plotted then it's better to use the hexagonal layout or a larger scale for more resolution. Is there a use case not covered otherwise?

**Comment by svrnwnsch** [comment]
See the following picture: ![rps](https://user-images.githubusercontent.com/1852828/29118854-0b063f18-7d04-11e7-9f2f-0398557bfb70.png)
The maximum data value is around 0,14 while the surrounding values reduce that to a plotted value 0,06.
This makes the picture necessary dark as it would be fine to set the maximum value of the colorbar to 0.06.

**Comment by marcharper** [comment]
Did you try a hexagonal plot?

**Comment by marcharper** [comment]
If you want the colors to be lower than the extremes you could also take the log before plotting.

**Comment by fairliereese** [comment]
Just wanted to throw in my two cents saying that I think what OP suggested should be the default behavior. Even logging the underlying values does not necessarily make the colorbar make sense.

**Comment by fairliereese** [comment]
I forked the repo and added a few lines of code to support this: https://github.com/fairliereese/python-ternary. If you want me to submit a PR I will.

**Comment by marcharper** [comment]
@fairliereese Sure, happy to take a look.
