### ISSUE TITLE
Clear the plot

### ISSUE THREAD

**Issue by wirebound** [marcharper/python-ternary#71]
Hello,
thank you very much for the development of the package. It's helping me a lot.
I am having some difficulties clearing the figures while I am writing and saving them dynamically, because I can't get clf() or close() working. So right now, data points from previous loops are piling up in later figures. I hope, I made my example readable... (I am working with subplots though I don't really need it to fulfill some required formatting, that I haven't been able to accomplish without it):

```
import ternary
import matplotlib.pyplot as plt

list1 = ...
list2 = ...
list3 = ...
list4 = ...
marker_list = ...
color_list = ...

for val1 in list1:
    for val2 in list2: 
        for val3 in list3:
             w0 = ... # val2 and val3 required
             w1 = ... # val2 and val3 required
             w2 = ... # val2 and val3 required
             point_dict[val3].append((w0,w1,w2))

    # Boundary and Gridlines
    scale = 1.0
    figure, ax = plt.subplots(figsize=(12,10.5))
    tax = ternary.TernaryAxesSubplot(scale=scale,ax=ax)

    # Draw Boundary and Gridlines
    ...
    # Set Axis labels and Title
    ...

    # Plot in different styles with a legend
    for val3 in list3:
        tax.scatter(point_dict[list3[val3]], marker=marker_list[val3], 
                        color=color_list[val3],label=item)
            
    file_title = str(list4[val1])
    print file_title
    tax._redraw_labels()
    plt.savefig(file_title+'K.png')
    plt.close('all')
    plt.clf()
```

Whatever I fill in in the last lines, it won't reset the plot. However, it must be reset before I enter loop 1 ('for val1 in list1:') again. Right now, my only choise is to run and exit the .py to change val1 manually.

Any suggestions would be appreciated!

**Comment by marcharper** [comment]
Can you try `tax.close()`? Also, are you resetting `point_dict` in each iteration?

**Comment by wirebound** [comment]
Hello marcharper,
thanks that you took some of your time to answer my question and for your fast response. I am a little bit embarressed... I've really forgotten to reset my dict.
Concerning `tax.close()`: it results in 
> AttributeError: 'TernaryAxesSubplot' object has no attribute 'close'
However, I don't need any of this commands any more. If I reset the dict it's just working perfectly. Thanks again!

**Comment by marcharper** [comment]
Great. FYI `tax.close()` only works on the latest version (here on github), I haven't pushed it to pypi yet (will soon...)
