### ISSUE TITLE
Ask: Sharing the same color-bar between several ternary graphs

### ISSUE THREAD

**Issue by akinori8888** [marcharper/python-ternary#72]
I want to share color-bar between several ternary graphs which have individual value-range. 
For example, value-range of graph A is (0, 67), value-range of graph B is (65, 202)
I want the color-bar which fits both of graph A and graph B.

Now, I have two color-bars and set of (color and number) does not match between A and B

**Comment by marcharper** [comment]
You can pass in parameters for the color bar limits (vmax and vmin), see [here](https://stackoverflow.com/questions/13784201/matplotlib-2-subplots-1-colorbar).

If you want one colorbar for all your plots, that's controllable by matplotlib, try [this link](https://stackoverflow.com/questions/13784201/matplotlib-2-subplots-1-colorbar) or search for similar.

**Comment by akinori8888** [comment]
I really appreciate your answer, I'll try that.

**Comment by akinori8888** [comment]
Additional question, sorry.
Is there any function to describe the number in heatmap like the picture below in python-ternary?
![default](https://user-images.githubusercontent.com/30164982/31261773-46c5f344-aa91-11e7-8cfd-183c7a6fbc5a.png)

**Comment by akinori8888** [comment]
Sorry for successive questions. I tried following to your answer, but there are three questions.
I could set vmin and vmax

1. How to delete ticks outside the figure, vertical and horizontal ticks of (0,2,4,6,8,10)?

2. How can I set ticks numbers from (1,2,3,4,5,6,7,8,9,10) to (0.1,0.2,0.3,0.4 ....) ? 

3. How to create subplots and put ternary graph inside the subplots? this is related to the previous question.

![image](https://user-images.githubusercontent.com/30164982/31267807-92b0fede-aab4-11e7-8c64-35e4c5697f85.png)

**Comment by marcharper** [comment]
> Is there any function to describe the number in each cell of heatmap like the picture below in python-ternary?

There's not a built in function but you could supply the coordinates and use `tax.annotate(...)` to directly add the text.

>1. How to delete ticks outside the figure, vertical and horizontal ticks of (0,2,4,6,8,10)?

You can turn off matplotlib's axis ticks with

```
tax.clear_matplotlib_ticks()
```
>2. How can I set ticks numbers from (1,2,3,4,5,6,7,8,9,10) to (0.1,0.2,0.3,0.4 ....) ?

You can change the scaling or overwrite the tick values directly. See this [example](https://github.com/marcharper/python-ternary/blob/master/examples/custom_axis_scaling.py).

> How to create subplots and put ternary graph inside the subplots? this is related to the previous question.

You can wrap the matplotlib axis for the subplot like so:
```
 figure, ax = pyplot.subplots()
    tax = ternary.TernaryAxesSubplot(ax=ax)
```

Or using `gridspec`:
```
   from matplotlib import pyplot, gridspec

    pyplot.figure()
    gs = gridspec.GridSpec(2,2)
    ax = pyplot.subplot(gs[0,0])
    figure, tax = ternary.figure(ax=ax)
```

**Comment by akinori8888** [comment]
Thanks for your kind answer, I made it!

**Comment by marcharper** [comment]
If you'd like to contribute a plot to the examples please let me know!
