### ISSUE TITLE
Request: add individual point color to scatter

### ISSUE THREAD

**Issue by tantrev** [marcharper/python-ternary#75]
It would just be nice to be able to make a scatter plot with individually colored points.

**Comment by marcharper** [comment]
Hi @tantrev 

You should be able to do this now. Ternary passes through most options to matplotlib and you can [specify individual colors](https://stackoverflow.com/questions/12236566/setting-different-color-for-each-series-in-scatter-plot-on-matplotlib) for scatter plot points with matplotlib like so:

```
import matplotlib.pyplot as plt
plt.scatter([1,2,3],[4,5,6],color=['red','green','blue'])
```

You can specify the colors in any standard matplotlib way (RGB values or using a colormap) to ternary's scatter method in the same way in the `color` parameter.

**Comment by marcharper** [comment]
Here's a quick example:

```
import random
import ternary

colors = ['r', 'g', 'b']

def random_points(num_points=25, scale=40):
    points = []
    for i in range(num_points):
        x = random.randint(1, scale)
        y = random.randint(0, scale - x)
        z = scale - x - y
        points.append((x,y,z))
    return points

### Scatter Plot
scale = 40
figure, tax = ternary.figure(scale=scale)
tax.set_title("Scatter Plot", fontsize=20)
tax.boundary(linewidth=2.0)
tax.gridlines(multiple=5, color="blue")
# Plot a few different styles with a legend
points = random_points(30, scale=scale)
color = [random.choice(colors) for _ in range(30)]
tax.scatter(points, marker='s', color=color, label="Random Colors")
tax.legend()
tax.ticks(axis='lbr', linewidth=1, multiple=5)

tax.show()
```

**Comment by Alejobep** [comment]
Hi,

Thanks for your reply.

I wused one of the examples in github and though I managed to get a colorbar, I am confused about all the kwargs I included since I just copied someone else's code without fully comprehending the meaining of each parameter and whether they were necessary or not.

Why is it necessary to declare `cm=`, `c=` and `colormap=`. If I remove some I miss the colorbar.

Regarding the normalization I used the logarithm because i could not figure out how to do it. 

Thanks. Pasting my code below


```
import ternary
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

cm = plt.cm.get_cmap('viridis')


dat=pd.DataFrame(columns=list('XYZV'))

dat['X']=random.sample(range(45),10)
dat['Y']=random.sample(range(45),10)
dat['Z']=100-(dat['X']+dat['Y'])
dat['V']=10**np.random.randint(0,high=10,size=10)/1e5



# sc = plt.scatter(dat.X, dat.Y, c=dat.V, vmin=0, vmax=7, s=35, cmap=cm)



scale=100



fig, tax = ternary.figure(scale=scale)
fig.set_size_inches(10, 9)

points=dat[['X','Y','Z']].values


minv=np.log10(dat.V.min())
maxv=np.log10(dat.V.max())

tax.scatter(points,s=60,vmin=minv,vmax=maxv,colormap=plt.cm.viridis,colorbar=True,c=np.log10(dat['V'].values),cmap=plt.cm.viridis)


# Decoration.
tax.boundary(linewidth=1)
tax.gridlines(multiple=10, color="gray")
tax.ticks(axis='lbr', linewidth=1, multiple=20)
tax.get_axes().axis('off')

```
