### ISSUE TITLE
How to change the size of text of color label?

### ISSUE THREAD

**Issue by akinori8888** [marcharper/python-ternary#76]
How to change the size of text of color label in using heatmap?
I searched in previous discussions, but could not find it.

I think if I can get the object of colorbar, I can change the fontsize of it by using an order like below.
"ax.set_yticklabels( fontsize=10)"
,but I don't know how to get it.

And another question, in this case, what is corresponding to the "im" in the [code](https://stackoverflow.com/questions/13784201/matplotlib-2-subplots-1-colorbar) below?
When putting one color bar to subplots, "im" is needed to have the colorbar, but again I cannot find it.

```
fig, axes = plt.subplots(nrows=1, ncols=3, figsize=(9.75, 3))
for ax in axes.flat:
    im = ax.imshow(np.random.random((10,10)), vmin=0, vmax=1)
fig.colorbar(im, ax=axes.ravel().tolist())
plt.show()
```

**Comment by marcharper** [comment]
```
figure, tax = ternary.figure()
tax.heatmap(..., colorbar=True)  # colorbar is on by default
tax.ticks(..., fontsize=10)
```
See [here](https://github.com/marcharper/python-ternary/blob/master/ternary/ternary_axes_subplot.py#L304) for the function that sets the axis ticks.

**Comment by akinori8888** [comment]
Thanks for replying, but it does not work well.
I wanna increase the text size of colorbar, but other numbers show up around the triangle instead.
And at the same time, labels were disappeared when saving as png. Why is this?

I added this code. `    tax.ticks(fontsize=25)`

Disappeared labels: 
`    tax.left_axis_label("$A$", offset=0.13, fontsize=20)
    tax.right_axis_label("$B$", offset=0.13 , fontsize=20)
    tax.bottom_axis_label("$C$", offset=0.01, fontsize=20)`

![1](https://user-images.githubusercontent.com/30164982/34162723-109690fa-e518-11e7-99a8-accff962a20c.png)

**Comment by akinori8888** [comment]
I could solve the label problem by using  `tax._redraw_labels()`  in the issue of [this](https://github.com/marcharper/python-ternary/issues/36)

**Comment by marcharper** [comment]
You can pass through colorbar specific parameters in the colorbar_kw argument (it's a dictionary). There is an example [here](https://github.com/marcharper/python-ternary/blob/master/examples/colorbar_kwargs.py).
