### ISSUE TITLE
Add non-equal axis scales

### ISSUE THREAD

**Issue by ibell** [marcharper/python-ternary#77]
Ah this is so close to exactly what I need for ternary plotting, but I have the issue that the bottom axis needs to be of a very different scale than the others.  I can do the variable transformation myself, but I'd rather not if I can avoid it.

Anyway, my use case is this:
bottom axis goes from 0 to 1000, left axis goes from 1000 to 3000, right axis goes from 2 to 6.  

It seems that is not possible so far as I can tell?  That's how I understand this comment: https://github.com/marcharper/python-ternary/blob/master/examples/custom_axis_scaling.py#L22-L29

**Comment by marcharper** [comment]
Scaling is your best bet, you can overwrite the axis labels if you want. However to provide qualitatively different axes in a native way would require a refactor from one scale parameter to three.

**Comment by ibell** [comment]
Got it, I'll do that.  I figured that was the issue (one versus three scale
parameters).

I'm totally confused by these ternary plots.  Either its a bug in my brain
or a bug in the library, but I don't understand which axes the first,
second, and third inputs are plotted on.  An input (0.25, 0, 0) with all
defaults should be on the bottom left of the figure, correct?  The order of
axes is bottom, right, left for inputs 1,2,3?  I'll show some examples
tomorrow demonstrating the problems I am having.

**Comment by marcharper** [comment]
Checkout the readme section on orientation -- there are multiple valid ways to interpret the plotting directions and the library gives you a lot of control over it.
