### ISSUE TITLE
Length of the triangle sides - height of the triangle

### ISSUE THREAD

**Issue by stateroom** [marcharper/python-ternary#84]
First of all, thank you for this very useful python tool! I used it to create the following plot.

![pyx_all](https://user-images.githubusercontent.com/38553093/39037925-4420e46a-4482-11e8-9696-dcfa8e8454ab.png)

Unfortunately, the diagram looks compressed in height. So my first question is, how can I change that (making the triangle higher, without changing the width)?
The second question concerns the new corner label function. Do I have to install the new branch to use it? At the moment I am using the master. For the example code of the diagram see below.

```
import ternary

### Scatter Plot
scale = 100
figure, tax = ternary.figure(scale=scale)
tax.set_title("NWA O266", fontsize=15)
tax.boundary(linewidth=1.0)
tax.gridlines(multiple=10, color="blue", linewidth=0.2)

# Remove outer axis
tax.ax.axis("off")

# Set Axis labels and Title
fontsize = 15
#tax.set_title("Simplex Boundary and Gridlines", fontsize=fontsize)
tax.left_axis_label("$\longleftarrow$ Mg", fontsize=fontsize)
tax.right_axis_label("$\longleftarrow$ Ca", fontsize=fontsize)
tax.bottom_axis_label("Fe $\longrightarrow$", fontsize=fontsize)

# Draw lines parallel to the axes
tax.horizontal_line(45, color='green', linewidth=0.7, linestyle="--")
tax.horizontal_line(20, color='green', linewidth=0.7, linestyle="--")
tax.horizontal_line(5, color='green', linewidth=0.7, linestyle="--")

# Plot a few different styles with a legend
points = [(55.3,20.9,23.8),
(65,7.8,27),
(47.6,23.4,29),
(66.3,7.8,25.9),
(47.6,24.9,27.6),
(66.7,5.1,28.1),
(47.5,24,28.5),
(67.8,6.8,25.5),
(47.3,25.9,26.8),
(65.4,8.9,25.8),
(52,22.6,25.3),
(69.2,4.8,26)]
tax.scatter(points, marker='x', color='red', label="Pyroxenes all")
tax.legend()
tax.ticks(axis='lbr', linewidth=0.5, multiple=20, fontsize=5)

 # Remove default Matplotlib Axes
tax.clear_matplotlib_ticks()

tax.savefig('Pyx_all.png', dpi=400)```

**Comment by marcharper** [comment]
For the corners, the master and the latest release 1.0.4 have the new code.

For the height / proportions, you can resize the image by using `plt.show()` interactively) instead of `savefig`), or explicitly set the dimensions of the figure using standard matplotlib functions. Try something like:

```
fig, ax = plt.subplots(figsize=(12, 8))
tax = ternary.TernaryAxesSubplot(ax=ax)
...
```
