### ISSUE TITLE
weird things of heat map when scale = 1.0

### ISSUE THREAD

**Issue by xindi-dumbledore** [marcharper/python-ternary#86]
I'm trying the code given in one of the examples:

```
def generate_random_heatmap_data(scale=5):
    from ternary.helpers import simplex_iterator
    d = dict()
    for (i,j,k) in simplex_iterator(scale):
        d[(i,j)] = random.random()
    return d

scale = 20
d = generate_random_heatmap_data(scale)
figure, tax = ternary.figure(scale=scale)
tax.heatmap(d, style="h")
tax.boundary()
tax.set_title("Heatmap Test: Hexagonal")
```

When I change the scale to 1, I got very weird plot:

![image](https://user-images.githubusercontent.com/31557294/39545195-7075460a-4e1e-11e8-9f89-ea9fbacc68c8.png)

What is the reason behind this?

My guess is that the simplex_iterator(scale) would just output a dictionary with keys (0,0),(0,1),(1,0), making the heat map hard to do interpolation. But I fed in my own dictionary with additional keys, like(0.5,0.2), (0.3,0.2), etc. it still output plots as weird as this one.

**Comment by xindi-dumbledore** [comment]
ah I think I made a mistake here for the original example... But for my own case, I still have very weird thing out put if I do:

{(0, 0): 0.8089006956241045,
 (0, 1): 0.8906146926138482,
 (0.4, 0.2): 0.8,
 (0.5, 0.5): 0.2,
 (1, 0): 0.3636529471708466}

<img width="354" alt="image" src="https://user-images.githubusercontent.com/31557294/39545710-0b4ae12a-4e20-11e8-80c9-b9582340aa72.png">

**Comment by marcharper** [comment]
For the heatmaps you can't really use `scale=1`. The heatmap is actually just a bunch of polygons for a specific partitioning of the simplex based on the scale parameter. The library doesn't support heatmaps for arbitrary points; if that's what you need it's better to use `heatmapf` and supply an interpolation function.

It's fine to use `scale=1` for scatter plots and curves.
