### ISSUE TITLE
Problem of including heatmap in a subplot

### ISSUE THREAD

**Issue by xindi-dumbledore** [marcharper/python-ternary#87]
I'm encountering a problem when including the heatmap:

When I'm doing this:

```
figure, tax = ternary.figure(scale=scale)
tax.boundary()
tax.heatmap(heatmap_dic_correct, style="d")
tax.ticks(axis='lbr', multiple = 1,tick_formats="%.1f",linewidth=1)# ticks = list(np.linspace(0,1,11))
tax.bottom_axis_label("Author", fontsize=fontsize)
tax.right_axis_label("Book", fontsize=fontsize, offset = 0.1)
tax.left_axis_label("Publisher", fontsize=fontsize, offset = 0.1)
tax.clear_matplotlib_ticks()
for spine in plt.gca().spines.values():
    spine.set_visible(False)
tax.get_axes().axis("off")
tax.set_title("%s"%bisac_mapping[genre], fontsize = fontsize)
```

It works greatly, producing this:

![image](https://user-images.githubusercontent.com/31557294/39555857-3e61ac36-4e4a-11e8-81e9-129fb2e39a7f.png)

However, when I try to put it into a subplot by doing this:
```
figure, ax = plt.subplots()
tax = ternary.TernaryAxesSubplot(ax=ax)
# tax.boundary()
tax.heatmap(heatmap_dic_correct, style="d")
tax.ticks(axis='lbr', multiple = 1,tick_formats="%.1f",linewidth=1)# ticks = list(np.linspace(0,1,11))
tax.bottom_axis_label("Author", fontsize=fontsize)
tax.right_axis_label("Book", fontsize=fontsize, offset = 0.1)
tax.left_axis_label("Publisher", fontsize=fontsize, offset = 0.1)
tax.clear_matplotlib_ticks()
for spine in plt.gca().spines.values():
    spine.set_visible(False)
tax.get_axes().axis("off")
tax.set_title("%s"%bisac_mapping[genre], fontsize = fontsize)
```

It produces this :(

![image](https://user-images.githubusercontent.com/31557294/39555878-5ff92234-4e4a-11e8-9dbd-c125921a3823.png)

The dictionary I put in is:
`heatmap_dic_correct = {(1, 3): 8.0, (3, 0): 1.0, (8, 0): 18.0, (3, 2): 20.0, (0, 7): 15.0, (0, 0): 102.0, (1, 6): 13.0, (5, 1): 8.0, (0, 3): 17.0, (2, 5): 8.0, (7, 2): 22.0, (4, 0): 9.0, (1, 2): 7.0, (9, 0): 33.0, (2, 0): 7.0, (8, 1): 21.0, (4, 4): 23.0, (6, 3): 14.0, (1, 5): 3.0, (5, 0): 8.0, (0, 4): 17.0, (3, 3): 65.0, (5, 3): 9.0, (4, 1): 8.0, (1, 1): 17.0, (5, 4): 15.0, (2, 6): 15.0, (2, 7): 18.0, (7, 1): 17.0, (4, 5): 21.0, (2, 2): 9.0, (6, 0): 7.0, (1, 4): 16.0, (2, 1): 4.0, (2, 3): 21.0, (4, 2): 15.0, (1, 0): 11.0, (0, 8): 42.0, (3, 5): 13.0, (0, 1): 19.0, (7, 0): 10.0, (3, 6): 18.0, (3, 4): 15.0, (6, 1): 11.0, (3, 1): 10.0, (0, 2): 10.0, (0, 6): 11.0, (1, 8): 36.0, (6, 2): 12.0, (4, 3): 27.0, (1, 7): 24.0, (0, 9): 172.0, (0, 5): 18.0, (5, 2): 9.0, (2, 4): 12.0}`

Any direction on where the problem may be in? Thanks!

**Comment by marcharper** [comment]
The scale is off. The dictionaries are not automatically normalized since it's not obvious what scale would be appropriate when x + y + z = scale if only x and y are specified.

**Comment by marcharper** [comment]
Try entering the scale in the line:
```tax = ternary.TernaryAxesSubplot(ax=ax)```
