### ISSUE TITLE
Directional Ternary

### ISSUE THREAD

**Issue by fredmarlton** [marcharper/python-ternary#91]
Hi @marcharper (and others),

I'm doing a ternary phase diagram, but I would like the colour to represent direction. So, I have x,y,z data for the three different ternary axes, but I also have x,y,z data for the colour map. I was hoping to plot the x,y,z as r,b,g and alpha (where alpha is transparency and would correspond to a magnitude). Any ideas on how I could do this?

Thanks,
Fred

**Comment by marcharper** [comment]
There's an example near the bottom of the readme that shows how to use RGBA values for the colors. I think that should do what you want.

**Comment by fredmarlton** [comment]
Awesome, thanks!

**Comment by fredmarlton** [comment]
Hey, I'm sure if I'm making a silly mistake somewhere, but I'm getting the following error when going through that example: TypeError: heatmap() got an unexpected keyword argument 'use_rgba'

**Comment by marcharper** [comment]
Does the [notebook](https://github.com/marcharper/python-ternary/blob/master/examples/Ternary-Examples.ipynb) work for you? I added the RGBA example at the end and it seems to work fine.

**Comment by fredmarlton** [comment]
Hey, so it's still not working. All of the other examples in the notebook work fine. I checked my heatmapping.py file in "\anaconda3\Lib\site-packages\ternary" and it seems to be missing the use_rgba parameter (see image below). I tried re-installing the package using the conda method, but it's still not there. I could probably do some sort of work around to get this working, but I thought it would be good to sort this out in case it happens to someone else as well. 

![image](https://user-images.githubusercontent.com/40761740/47002793-2ee10600-d12e-11e8-84c6-fd6d876f0a7b.png)

**Comment by marcharper** [comment]
The conda-forge release is just outdated wrt to the documentation and examples. I'll push a new release and see if it gets picked up by conda. You can also install directly from the master branch / github.

**Comment by fredmarlton** [comment]
Actually, I'm not sure I gave the right description of what I want to achieve. I want to do a rgba scatter on a ternary, is this possible using python-ternary? Wasn't sure as it seems to not be based upon the previous issue that was raised.

**Comment by fredmarlton** [comment]
Awesome, thanks!
