### ISSUE TITLE
Colorbar label size

### ISSUE THREAD

**Issue by llimonta** [marcharper/python-ternary#93]
How do you change the label size for the colorbar?

e.g.

`    b_kwargs = {"shrink" : 1.0,
             "pad" : 0.05,
             "aspect" : 15,
             "fraction":0.1}

    tax.heatmapf(f, boundary=True,
            style="hexagonal", cmap=plt.cm.get_cmap('jet'),scientific=False,cbarlabel='beta',vmin=0,vmax=0.6,cb_kwargs=b_kwargs)`

Adding fontsize/labelsize doesn't work.

**Comment by marcharper** [comment]
I think the issue is that you need at act directly on the label of the matplotlib axes object associated to the colorbar, which you don't have access to.

I can make a small change so that the colorbar can be accessed after plotting in via `tax.cbar`:

```
fig, tax = ternary.figure()
tax.heatmap(...)
...
# act directly on the colobar to change the font size / text / etc
tax.cbar.set_label(...)
```

**Comment by BlackWhiteHead** [comment]
This is a way may solve your problem
```
h = tax.heatmapf(f, boundary=True, style="hexagonal", colorbar=False, cmap=plt.cm.get_cmap('jet'),scientific=False,cbarlabel='beta',vmin=0,vmax=0.6,cb_kwargs=b_kwargs)
cb = h.figure.colorbar(h.collections[0])
cb.tick_params(labelsize=20)
```

**Comment by marcharper** [comment]
Thanks. I should have updated the issue after adding `cb_kwargs`.

**Comment by DS-Wen** [comment]
Hi, I'm also trying to use the colorbar kwargs. I saw nice colorbar labels in the latest example. Is it available now?

**Comment by marcharper** [comment]
You can use `cb_kwargs` as in the comment above. It's in the latest releases.
