### ISSUE TITLE
change plot symbols in Piper diagram

### ISSUE THREAD

**Issue by StefanoMenichetti** [marcharper/python-ternary#95]
Hallo at all, unlucky for me the Piper plot produce two similar symbols.
As you can see green circle stand for "Pozzo 4" as for "Pozzo D" ... maybe distinguish for size ?

Can I modify them ?

![piper](https://user-images.githubusercontent.com/36763460/51490275-11fe4380-1dab-11e9-9034-68d84ad6094c.png)

**Comment by marcharper** [comment]
Are you sure these plots were made by this library?

**Comment by StefanoMenichetti** [comment]
Sure it comes from Midvatten plugin, Piper menu.
<img width="292" alt="immagine" src="https://user-images.githubusercontent.com/36763460/51523691-875e2880-1e2c-11e9-9040-394b1f06f9bf.png">

**Comment by marcharper** [comment]
I think there's some confusion, this library is unrelated and has no GUI.
